In [1]:
#import the required libraries
import numpy as np

# Step 1 : Read the Data!

In [4]:
#Create file

filename = "Census.csv"

In [6]:
census= np.genfromtxt("makeSenseOfCensus.csv" , delimiter="," , skip_header=1)
print (census)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [8]:
data = np.genfromtxt("makeSenseOfCensus.csv", delimiter = "," , skip_header = 1)
print("\nData:\n\n ", data)


Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [9]:
#print the type of data
type(census)

numpy.ndarray

# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [16]:
new_record = [[50,9,4,1,0,0,40,0]]

np.concatenate((census,new_record),axis=0)

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [50.,  9.,  4., ...,  0., 40.,  0.],
       [60.,  9.,  4., ...,  0., 30.,  0.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [17]:
new_record = [[60,9,4,1,0,0,30,0]]

census=np.concatenate((census,new_record),axis=0)

In [19]:
census

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [50.,  9.,  4., ...,  0., 40.,  0.],
       [60.,  9.,  4., ...,  0., 30.,  0.],
       [60.,  9.,  4., ...,  0., 30.,  0.]])

# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [25]:
age = census[:,0]
age_1 = census [:,1]
print (age)
print (age_1)

[39. 50. 38. ... 50. 60. 60.]
[13. 13.  9. ...  9.  9.  9.]


Find the max age and store it in a variable called 'max_age'.



In [26]:
#print the max_age
max_age= age.max()
max_age

90.0

Find the min age and store it in a variable called 'min_age'.

In [27]:
#print the min_age
min_age = age.min()
min_age

17.0

Find the mean of the age and store it in a variable called 'age_mean'.

In [28]:
#print the age_mean
age_mean = age.mean()
age_mean

38.10667996011964

Find the standard deviation of the age and store it in a variable called 'age_std'

In [29]:
#print the age_std
age_std = age.std()
age_std

13.364048483474654

# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [30]:
race0=census[census[:,2]==0]
race1=census[census[:,2]==1]
race2=census[census[:,2]==2]
race3=census[census[:,2]==3]
race4=census[census[:,2]==4]

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [31]:
#len_0
len_0 = len(race0)
len_0

10

In [32]:
#len_1
len_1 = len(race1)
len_1

27

In [33]:
#len_2
len_2 = len(race2)
len_2

110

In [34]:
#len_3
len_3 = len(race3)
len_3

6

In [35]:
#len_4
len_4 = len(race4)
len_4

850

Find out which is the race with the minimum no. of citizens

In [36]:
dict1={
    0: len(race0),
    1: len(race1),
    2: len(race2),
    3: len(race3),
    4: len(race4)
}
minority_race_min = min(dict1, key=dict1.get)
minority_race_min

3

Find out which is the race with the minimum no. of citizens

In [37]:
majority_race_min = max(dict1, key=dict1.get)
majority_race_min

4

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [38]:
dict1[minority_race_min]

6

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [39]:
dict1[majority_race_min]

850

# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [41]:
senior_citizens = census[census[:,0]>60]
senior_citizens=senior_citizens.astype(int)
print (senior_citizens)

[[   79    10     4     1     0     0    20     0]
 [   67     6     4     1     0     0     2     0]
 [   76    14     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     0]
 [   70    10     4     1     0     0    40     0]
 [   64     7     4     1     0  2179    40     0]
 [   71    10     2     1     0  1816     2     0]
 [   68     2     4     0     0     0    20     0]
 [   66    11     4     0     0     0    20     0]
 [   64     2     4     1     0     0    40     0]
 [   90     9     2     1     0  2206    40     0]
 [   66     9     4     1  1409     0    50     0]
 [   75    11     4     0     0     0    20     0]
 [   65     9     4     0     0     0    40     0]
 [   64     9     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     1]
 [   65     9     4     1     0     0    16     0]
 [   77    10     4     1     0     0    40     0]
 [   62     9     4     0     0     0    24     0]
 [   76    14     4     1     0

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [44]:
working_hours_sum = np.sum(senior_citizens[:,6])
print (working_hours_sum)

1917


c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [47]:
senior_citizens_len = len(senior_citizens)
print (senior_citizens_len)

61


d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [48]:
avg_working_hours = working_hours_sum/senior_citizens_len
print (avg_working_hours)

31.42622950819672


e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [49]:
if avg_working_hours<25:
    print("Govt Policy is followed!")
else:
    print("Govt Policy is not followed!")

Govt Policy is not followed!


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [50]:
high = census[census[:,1]>10]
low =  census[census[:,1]<10]
low

array([[38.,  9.,  4., ...,  0., 40.,  0.],
       [53.,  7.,  2., ...,  0., 40.,  0.],
       [49.,  5.,  2., ...,  0., 16.,  0.],
       ...,
       [50.,  9.,  4., ...,  0., 40.,  0.],
       [60.,  9.,  4., ...,  0., 30.,  0.],
       [60.,  9.,  4., ...,  0., 30.,  0.]])

Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [51]:
high[:,7].mean()

0.42813455657492355

In [52]:
low[:,7].mean()

0.12638580931263857